version: "3.7"
services:

  mongo:
    image: mongo:4.4

  test-environment:
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile-environment
    image: caronte-test-environment

  test-backend:
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile-backend
    image: caronte-test-backend
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      TEST_ENVIRONMENT_HOST: test-environment
      TEST_ENVIRONMENT_SSH_PORT: 22
      TEST_ENVIRONMENT_HTTP_PORT: 8080

  test-frontend:
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile-frontend
    image: caronte-test-frontend
